import network
import socket
import time
from machine import Pin

alphaD1 = Pin(1,Pin.OUT)
alphaD2 = Pin(2,Pin.OUT)
alphaD3 = Pin(3,Pin.OUT)
alphaD4 = Pin(4,Pin.OUT)
alphaD5 = Pin(5,Pin.OUT)
alphaD6 = Pin(6,Pin.OUT)
alphaD7 = Pin(7,Pin.OUT)
alphaD8 = Pin(8,Pin.OUT)
alphaD9 = Pin(9,Pin.OUT)
alphaD10 = Pin(10,Pin.OUT)
alphaD11 = Pin(11,Pin.OUT)
alphaD12 = Pin(12,Pin.OUT)
alphaD13 = Pin(13,Pin.OUT)
alphaD14= Pin(14,Pin.OUT)
alphaD15= Pin(21,Pin.OUT)
alphaD16= Pin(22,Pin.OUT)
alphaD17= Pin(23,Pin.OUT)
alphaD18= Pin(24,Pin.OUT)
alphaD19= Pin(25,Pin.OUT)
alphaD20= Pin(26,Pin.OUT)

def alphaDisplay(char):
    if char=='A':
        alphaD1.value(0)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(0)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(0)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(0)
        alphaD19.value(0)
        alphaD20.value(1)
    elif char=='B':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(0)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(0)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(0)
    elif char=='C':
        alphaD1.value(0)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(0)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(0)
        alphaD12.value(0)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(0)
        alphaD17.value(0)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(1)
    elif char=='D':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(0)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(0)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(0)
    elif char=='E':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(0)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(0)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(0)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(1)
    elif char=='F':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(0)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(0)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(0)
        alphaD17.value(1)
        alphaD18.value(0)
        alphaD19.value(0)
        alphaD20.value(0)
    elif char=='G':
        alphaD1.value(0)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(0)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(1)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(0)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(1)
    elif char=='H':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(0)
        alphaD19.value(0)
        alphaD20.value(1)
    elif char=='I':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(0)
        alphaD5.value(0)
        alphaD6.value(1)
        alphaD7.value(0)
        alphaD8.value(0)
        alphaD9.value(0)
        alphaD10.value(1)
        alphaD11.value(0)
        alphaD12.value(0)
        alphaD13.value(0)
        alphaD14.value(1)
        alphaD15.value(0)
        alphaD16.value(0)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(0)
    elif char=='J':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(0)
        alphaD6.value(0)
        alphaD7.value(1)
        alphaD8.value(0)
        alphaD9.value(0)
        alphaD10.value(0)
        alphaD11.value(1)
        alphaD12.value(0)
        alphaD13.value(0)
        alphaD14.value(0)
        alphaD15.value(1)
        alphaD16.value(0)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(0)
        alphaD20.value(0)
    elif char=='K':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(1)
        alphaD8.value(0)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(0)
        alphaD12.value(0)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(1)
        alphaD16.value(0)
        alphaD17.value(1)
        alphaD18.value(0)
        alphaD19.value(0)
        alphaD20.value(1)
    elif char=='L':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(0)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(0)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(0)
        alphaD12.value(0)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(0)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(1)
    elif char=='M':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(1)
        alphaD7.value(1)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(0)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(0)
        alphaD19.value(0)
        alphaD20.value(1)
    elif char=='N':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(1)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(1)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(0)
        alphaD19.value(0)
        alphaD20.value(1)
    elif char=='O':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(0)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(1)
    elif char=='P':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(0)
        alphaD17.value(1)
        alphaD18.value(0)
        alphaD19.value(0)
        alphaD20.value(0)
    elif char=='Q':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(0)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(1)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(1)
    elif char=='R':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(0)
        alphaD15.value(1)
        alphaD16.value(0)
        alphaD17.value(1)
        alphaD18.value(0)
        alphaD19.value(0)
        alphaD20.value(1)
    elif char=='S':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(0)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(1)
        alphaD13.value(0)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(1)
    elif char=='T':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(0)
        alphaD6.value(0)
        alphaD7.value(1)
        alphaD8.value(0)
        alphaD9.value(0)
        alphaD10.value(0)
        alphaD11.value(1)
        alphaD12.value(0)
        alphaD13.value(0)
        alphaD14.value(0)
        alphaD15.value(1)
        alphaD16.value(0)
        alphaD17.value(0)
        alphaD18.value(0)
        alphaD19.value(1)
        alphaD20.value(0)
    elif char=='U':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(0)
        alphaD12.value(1)
        alphaD13.value(0)
        alphaD14.value(0)
        alphaD15.value(0)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(1)
    elif char=='V':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(0)
        alphaD11.value(0)
        alphaD12.value(1)
        alphaD13.value(0)
        alphaD14.value(1)
        alphaD15.value(1)
        alphaD16.value(0)
        alphaD17.value(0)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(0)
    elif char=='W':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(1)
        alphaD5.value(1)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(1)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(1)
        alphaD13.value(1)
        alphaD14.value(1)
        alphaD15.value(1)
        alphaD16.value(1)
        alphaD17.value(1)
        alphaD18.value(0)
        alphaD19.value(0)
        alphaD20.value(1)
    elif char=='X':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(1)
        alphaD5.value(0)
        alphaD6.value(1)
        alphaD7.value(1)
        alphaD8.value(0)
        alphaD9.value(0)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(0)
        alphaD13.value(0)
        alphaD14.value(1)
        alphaD15.value(1)
        alphaD16.value(0)
        alphaD17.value(0)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(0)
    elif char=='Y':
        alphaD1.value(1)
        alphaD2.value(0)
        alphaD3.value(0)
        alphaD4.value(1)
        alphaD5.value(0)
        alphaD6.value(1)
        alphaD7.value(1)
        alphaD8.value(0)
        alphaD9.value(0)
        alphaD10.value(1)
        alphaD11.value(1)
        alphaD12.value(0)
        alphaD13.value(0)
        alphaD14.value(1)
        alphaD15.value(1)
        alphaD16.value(0)
        alphaD17.value(0)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(0)
    elif char=='Z':
        alphaD1.value(1)
        alphaD2.value(1)
        alphaD3.value(1)
        alphaD4.value(1)
        alphaD5.value(0)
        alphaD6.value(0)
        alphaD7.value(0)
        alphaD8.value(1)
        alphaD9.value(0)
        alphaD10.value(0)
        alphaD11.value(1)
        alphaD12.value(0)
        alphaD13.value(0)
        alphaD14.value(1)
        alphaD15.value(0)
        alphaD16.value(0)
        alphaD17.value(1)
        alphaD18.value(1)
        alphaD19.value(1)
        alphaD20.value(1)

























