import network
import socket
import time
from machine import Pin

brailleD1=Pin(17,Pin.OUT)
brailleD2=Pin(18,Pin.OUT)
brailleD3=Pin(19,Pin.OUT)
brailleD4=Pin(20,Pin.OUT)
brailleD5=Pin(21,Pin.OUT)
brailleD6=Pin(22,Pin.OUT)


motor1=Pin(1,Pin.OUT)
motor2=Pin(2,Pin.OUT)
motor3=Pin(3,Pin.OUT)
motor4=Pin(4,Pin.OUT)
motor5=Pin(5,Pin.OUT)
motor6=Pin(6,Pin.OUT)
motor7=Pin(7,Pin.OUT)
motor8=Pin(8,Pin.OUT)
motor9=Pin(9,Pin.OUT)
motor10=Pin(10,Pin.OUT)
motor11=Pin(11,Pin.OUT)
motor12=Pin(12,Pin.OUT)


def SendLetters():
    obj=input()
    for i in range(len(obj)):
        time.sleep(2)
        brailleDisplay(obj[i])


def brailleDisplay(char):
    print('printing',char,'to console')
    if char=='a' or char=='A':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,0,0,0,0,0])
    elif char=='b' or char=='B':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,0,1,0,0,0])
    elif char=='c' or char=='C':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,1,0,0,0,0])
    elif char=='d' or char=='D':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(0)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,1,0,1,0,0])
    elif char=='e' or char=='E':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(0)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,0,0,1,0,0])
    elif char=='f' or char=='F':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,1,1,0,0,0])
    elif char=='g' or char=='G':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,1,1,1,0,0])
    elif char=='h' or char=='H':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,0,1,1,0,0])
    elif char=='i' or char=='I':
        brailleD1.value(0)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([0,1,1,0,0,0])
    elif char=='j' or char=='J':
        brailleD1.value(0)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([0,1,1,1,0,0])
    elif char=='k' or char=='K':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([1,0,0,0,1,0])
    elif char=='l' or char=='L':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([1,0,1,0,1,0])
    elif char=='m' or char=='M':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([1,1,0,0,1,0])
    elif char=='n' or char=='N':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(0)
        brailleD4.value(1)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([1,1,0,1,1,0])
    elif char=='o' or char=='O':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(0)
        brailleD4.value(1)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([1,0,0,1,1,0])
    elif char=='p' or char=='P':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([1,1,1,0,1,0])
    elif char=='q' or char=='Q':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([1,1,1,1,1,0])
    elif char=='r' or char=='R':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([1,0,1,1,1,0])
    elif char=='s' or char=='S':
        brailleD1.value(0)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([0,1,1,0,1,0])
    elif char=='t' or char=='T':
        brailleD1.value(0)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([0,1,1,1,1,0])
    elif char=='u' or char=='U':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(1)
        brailleD6.value(1)
        motorDisplay([1,0,0,0,1,1])
    elif char=='v' or char=='V':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(1)
        brailleD6.value(1)
        motorDisplay([1,0,1,0,1,1])
    elif char=='w' or char=='W':
        brailleD1.value(0)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(1)
        motorDisplay([0,1,1,1,0,1])
    elif char=='x' or char=='X':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(1)
        brailleD6.value(1)
        motorDisplay([1,1,0,0,1,1])
    elif char=='y' or char=='Y':
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(0)
        brailleD4.value(1)
        brailleD5.value(1)
        brailleD6.value(1)
        motorDisplay([1,1,0,1,1,1])
    elif char=='z' or char=='Z':
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(0)
        brailleD4.value(1)
        brailleD5.value(1)
        brailleD6.value(1)
        motorDisplay([1,0,0,1,1,1])
    elif char==1:
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,0,0,0,0,0])
    elif char==2:
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,0,1,0,0,0])
    elif char==3:
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,1,0,0,0,0])
    elif char==4:
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(0)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,1,0,1,0,0])
    elif char==5:
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(1)
        brailleD6.value(0)
        motorDisplay([1,0,0,0,1,0])
    elif char==6:
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,1,1,0,0,0])
    elif char==7:
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,1,1,1,0,0])
    elif char==8:
        brailleD1.value(1)
        brailleD2.value(0)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([1,0,1,1,0,0])
    elif char==9:
        brailleD1.value(0)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([0,1,1,0,0,0])
    elif char==0:
        brailleD1.value(0)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([0,1,1,1,0,0])
    elif char==" ":
        brailleD1.value(0)
        brailleD2.value(0)
        brailleD3.value(0)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([0,0,0,0,0,0])
    elif char=='.':
        brailleD1.value(0)
        brailleD2.value(0)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(0)
        brailleD6.value(1)
        motorDisplay([0,0,1,1,0,1])
    elif char==',':
        brailleD1.value(0)
        brailleD2.value(0)
        brailleD3.value(1)
        brailleD4.value(0)
        brailleD5.value(0)
        brailleD6.value(0)
        motorDisplay([0,0,1,0,0,0])
    elif char=='#':
        brailleD1.value(0)
        brailleD2.value(1)
        brailleD3.value(0)
        brailleD4.value(1)
        brailleD5.value(1)
        brailleD6.value(1)
        motorDisplay([0,1,0,1,1,1])
    else:
        print('none')
        brailleD1.value(1)
        brailleD2.value(1)
        brailleD3.value(1)
        brailleD4.value(1)
        brailleD5.value(1)
        brailleD6.value(1)
        motorDisplay([1,1,1,1,1,1])
        

def motorDisplay(arr):
        print('executing cmd 1')
        motor1.value(arr[0])
        motor2.value(arr[1])
        motor3.value(arr[2])
        motor4.value(arr[3])
        motor5.value(arr[4])
        motor6.value(arr[5])
        motor7.value(0)
        motor8.value(0)
        motor9.value(0)
        motor10.value(0)
        motor11.value(0)
        motor12.value(0)
        time.sleep(1)
        
        print(arr)
        print('executing phase 2')
        motor1.value(arr[0])
        motor2.value(arr[1])
        motor3.value(arr[2])
        motor4.value(arr[3])
        motor5.value(arr[4])
        motor6.value(arr[5])
        motor7.value(0)
        motor8.value(0)
        motor9.value(0)
        motor10.value(0)
        motor11.value(0)
        motor12.value(0)
        time.sleep(1)
        print('phase 2 completed')
        motor1.value(0)
        motor2.value(0)
        motor3.value(0)
        motor4.value(0)
        motor5.value(0)
        motor6.value(0)
        motor7.value(0)
        motor8.value(0)
        motor9.value(0)
        motor10.value(0)
        motor11.value(0)
        motor12.value(0)
        print('all positions to default')
        
        
        
       
        
    

if __name__=="__main__":
    SendLetters()
    

    